# Generated by Django 3.2.2 on 2021-05-12 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'coupons',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='coupons',
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'usercoupons',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='coupons',
            field=models.ManyToManyField(through='users.UserCoupon', to='users.Coupon'),
        ),
    ]
