# Generated by Django 3.2.2 on 2021-05-14 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210512_0454'),
        ('users', '0003_alter_usercoupon_table'),
    ]

    operations = [
    ]
