# Generated by Django 3.2.2 on 2021-05-13 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210512_0513'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reviewimage',
            table='review_images',
        ),
    ]
