# Generated by Django 3.2.3 on 2021-05-19 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210517_1114'),
        ('reviews', '0003_auto_20210517_1108'),
    ]

    operations = [
    ]
