# Generated by Django 3.2.2 on 2021-05-16 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_reviewimage_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_image',
        ),
        migrations.AddField(
            model_name='reviewimage',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.review'),
        ),
    ]
