# Generated by Django 3.2.2 on 2021-05-14 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210512_0454'),
        ('reviews', '0003_alter_reviewimage_table'),
    ]

    operations = [
    ]
