# Generated by Django 3.2.2 on 2021-05-12 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210512_0454'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Selected_Product',
            new_name='SelectedProduct',
        ),
        migrations.AlterModelTable(
            name='selectedproduct',
            table='selectedproducts',
        ),
    ]
