# Generated by Django 3.2.3 on 2021-05-19 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210517_0821'),
        ('orders', '0002_auto_20210517_1114'),
    ]

    operations = [
    ]
