# Generated by Django 3.2.2 on 2021-05-16 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210516_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.status'),
        ),
    ]
