# Generated by Django 3.2.2 on 2021-05-16 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210516_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='status',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_phone_number',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
