# Generated by Django 3.2.2 on 2021-05-16 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210516_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.status'),
        ),
    ]
