# Generated by Django 3.2.2 on 2021-05-16 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20210516_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='status',
        ),
    ]
